### ISSUE TITLE
BR values to use

### ISSUE THREAD

**Issue by ram1123** [ram1123/flashggFinalFit#1]
Hi @atishelmanch, @chuwang1

Today, I observed that we are using slightly different values of BR. So, Let's fix this.

Current BF used  [here](https://github.com/atishelmanch/flashggFinalFit/blob/4cd85509567330d89901842c6e59772457fab9f5/Plots/FinalResults/plot_limits.py#L522-L523):

```python
    HHWWgg_qqlnu_factor = 6.983 # 1 / branching ratio of qqlnugg including electron and muon channels. Need to multiply measured XS by this to get measured XS of HH->WWgg production
    HHWWgg_WWgg_factor = 2061.43 # (1 / 0.0004851), 0.0004851 is BR of HH->WWgg
```

I am calculating it like this:

#### HH-> WWgg factor

- BR of H->WW = 0.215
- BR of H->gg = 0.00227

So, HHWWgg_WWgg_factor = (1.0/(0.215 x 0.00227)) = 1.0 / 0.00048805 = 2048.97

#### WW->lnuqq factor

- BR of H->Lnu = 0.3272
- BR of H->qq = 0.6741

So, HHWWgg_qqlnu_factor = 1/(0.3272 x 0.6741) = 1/0.22056552 = 4.53

#### WW->lnulnu factor

- BR of H->Lnu = 0.3272

So, HHWWgg_qqlnu_factor = 1/(0.3272 x 0.3272) = 1/0.10705984 = 9.34

#### WW->qqqq factor

- BR of H -> QQ = 0.6741

So, HHWWgg_qqqq_factor = 1/(0.6741 x 0.6741) = 1/0.45441081 = 2.20

Let me know if you think we need to update some numbers.

**Comment by atishelmanch** [comment]
Hello @ram1123 - For WW decays, we should refer to [pdgLive - W boson](https://pdglive.lbl.gov/Particle.action?node=S043&init=0) as we've agreed upon through mattermost chat. Here are some comments:

The qqlnu factor you've linked is from a May 12th commit which I left up for too long which included only electron and muon decays, and have since updated today [here](https://github.com/atishelmanch/flashggFinalFit/blob/e01fa5160b39e5a807b74b580e13aa1561e49f6d/Plots/FinalResults/plot_limits.py#L175). For your qqlnu factor, you are missing a factor of 2 in the BR calculation as you can get qqlnu from (W1->qq + W2->lnu) and (W1->lnu + W2->qq) with equal probabilities. The Semi-Leptonic channel is the only WW channel for which this combinatoric factor of 2 is included.

Using pdgLive linked above with the current values, I get the following factors:

BR(WW->qqlnu) = 2 * BR(W->qq) * BR(W->lnu) = 2 * (0.6741) * (0.1071 + 0.1063 + 0.1138) = 0.441
1 / BR(WW->qqlnu) = 2.27

BR(WW->lnulnu) = BR(W->lnu) * BR(W->lnu) = (0.1071 + 0.1063 + 0.1138)^2 = (0.3272)^2 = 0.107
1 / BR(WW->lnulnu) = 9.35

BR(WW->qqqq) = BR(W->qq) * BR(W->qq) = (0.6741)^2 = 0.454 
1 / BR(WW->qqqq) = 2.20

You can see similar values in the recent fggfinalfit code I committed where the branching ratios are added as rateParams to the datacards [here](https://github.com/atishelmanch/flashggFinalFit/blob/HHWWgg_Dev_runII_102x/HHWWggFinalFitScript.py#L106-L122). 

I am not sure what the difference between using lnu*3 vs. (enu + munu + taunu) BRs is. For now I propose using the above BRs for WW BRs barring pdgLive updates. What do you think @ram1123? Can you please link me where you got the H->WW and H->gg BRs? Once we decide on these let's close the issue. Thanks. 

cc: @chuwang1

**Comment by atishelmanch** [comment]
Dear @ram1123 and @chuwang1, 

I have set the branching ratios I think we should all use here: 

https://github.com/atishelmanch/flashggFinalFit/blob/HHWWgg_Dev_runII_102x/HHWWggFinalFitScript_Tools.py#L6-L35

Which are currently accessed [here](https://github.com/atishelmanch/flashggFinalFit/blob/HHWWgg_Dev_runII_102x/HHWWggFinalFitScript.py#L104-L107) and added to the datacards [here](https://github.com/atishelmanch/flashggFinalFit/blob/HHWWgg_Dev_runII_102x/HHWWggFinalFitScript.py#L113-L122). 

As mentioned before I got the W BR's from pdglive, and the Higgs mass from pdglive in order to determine which mass point to choose Higgs BR values from [here](https://twiki.cern.ch/twiki/bin/view/LHCPhysics/CERNYellowReportPageBR).

What do you think? Can we close this issue?

Thanks,
Abe

**Comment by ram1123** [comment]
Dear @atishelmanch,

I cross-check all the values and it seems fine and consistent with the latest values in the PDG and CERN Yellow report.

Also, it is good idea to add them in code like this. And we all should use this.

Now, we can close this issue.

Thanks,
Ram
